In [1]:
import numpy as np

# 1d array to list
arr = np.array([1, 2, 3])
print(f'NumPy Array:\n{arr}')

list1 = arr.tolist()
print(f'List: {list1}')


NumPy Array:
[1 2 3]
List: [1, 2, 3]


In [2]:
import numpy as np
m = np.arange(6).reshape(2,3)
print("Original matrix:")
print(m)
result =  np.trace(m)
print("Condition number of the said matrix:")
print(result)

Original matrix:
[[0 1 2]
 [3 4 5]]
Condition number of the said matrix:
4


In [22]:
import numpy as np
def higher ( a , x): 
    return a , a[a>x] , a[a>x] 

hi = higher (np.array([[1,2],[3,5]]) , 2)

In [23]:
hi

(array([[1, 2],
        [3, 5]]),
 array([3, 5]),
 array([3, 5]))

In [26]:
from numpy import array
a = array([[2  , 4],
           [4 , 5]])
print(a)
b =  array([[6  , 4],
           [8 , 3]])
print(b)
c = a + b
print(c)

[[2 4]
 [4 5]]
[[6 4]
 [8 3]]
[[ 8  8]
 [12  8]]


In [24]:
import numpy as np
print("Original matrix:\n")
X = np.random.rand(5, 10)
print(X)
print("\nSubtract the mean of each row of the said matrix:\n")
Y = X - X.mean(axis=1, keepdims=True)
print(Y)

Original matrix:

[[0.90445924 0.06660227 0.30558961 0.21243017 0.48386151 0.15482529
  0.45570449 0.61515543 0.73430395 0.28587958]
 [0.04835773 0.04123264 0.5094425  0.09399379 0.135452   0.33400366
  0.74077712 0.29592137 0.86919249 0.76423223]
 [0.52270137 0.46830892 0.23115656 0.72939995 0.06727162 0.27497662
  0.50158728 0.48832257 0.82239534 0.92999437]
 [0.92505724 0.25075158 0.20613228 0.7746175  0.24029815 0.70593446
  0.47061818 0.80046238 0.04734679 0.28744207]
 [0.46226809 0.08497941 0.20596391 0.56588853 0.47277086 0.63825399
  0.6084674  0.15027323 0.77645615 0.25263899]]

Subtract the mean of each row of the said matrix:

[[ 4.82578088e-01 -3.55278880e-01 -1.16291548e-01 -2.09450988e-01
   6.19803521e-02 -2.67055860e-01  3.38233387e-02  1.93274275e-01
   3.12422800e-01 -1.36001578e-01]
 [-3.34902826e-01 -3.42027907e-01  1.26181947e-01 -2.89266765e-01
  -2.47808549e-01 -4.92568954e-02  3.57516564e-01 -8.73391841e-02
   4.85931935e-01  3.80971681e-01]
 [ 1.90899096e-02 -3